version: '2.0'
services:
  frontend:
    build: 
      context: .
      dockerfile: ./frontend.Dockerfile
      
  backend:
    build: 
      context: .
      dockerfile: ./backend.Dockerfile

  nginx:
    image: nginx:1.24.0
    volumes:
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/public:/public:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - "1883:1883"
      - "8883:8883"

  postgres:
    image: postgres:16.0
    volumes:
      - postgres-db:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
    postgres-db:
