version: '2.0'
services:
  backend:
    build: 
      context: .
      dockerfile: ./backend.dev.Dockerfile
    command: npm run dev
    volumes:
      - backend-node-modules:/app/node_modules
      - ./backend:/app

  frontend:
    build: 
      context: .
      dockerfile: ./frontend.dev.Dockerfile
    command: npm run dev
    volumes:
      - frontend-node-modules:/app/node_modules
      - ./frontend:/app

volumes:
  backend-node-modules:
  frontend-node-modules:
